FIND_PACKAGE(Doxygen)

IF (DOXYGEN_FOUND)

SET(DOXYGEN_INPUT ${MAP_ROOT}/doc/doxygen/Doxyfile)
SET(DOXYGEN_OUTPUT ${MAP_ROOT}/build/doc/html/apidoc/index.html)
SET(transform2doxy ${MAP_ROOT}/tools/swig2doc/bin/transform2doxy)

set_property(GLOBAL PROPERTY ALLOW_DUPLICATE_CUSTOM_TARGETS 1)

# ADD_CUSTOM_TARGET(testR_Clibs
#  COMMAND ${R_EXECUTABLE} CMD build --no-docs ../../ 
#  COMMAND ${R_EXECUTABLE} CMD INSTALL --libs-only qtl_${RQTL_VERSION}.tar.gz 
#   COMMAND ${CMAKE_COMMAND} -E remove qtl_${RQTL_VERSION}.tar.gz
#   COMMAND ctest -R TestR)

# ADD_CUSTOM_COMMAND(
#   OUTPUT ${DOXYGEN_OUTPUT}
#   COMMAND ${CMAKE_COMMAND} -E echo_append "Building API Documentation..."
#   COMMAND ${DOXYGEN_EXECUTABLE} ${DOXYGEN_INPUT}
#   COMMAND ${CMAKE_COMMAND} -E echo "Done."
#   WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
#   DEPENDS ${DOXYGEN_INPUT}
#   )

# ADD_CUSTOM_TARGET(apidoc ALL DEPENDS ${DOXYGEN_OUTPUT})

# ADD_CUSTOM_TARGET(apidoc_forced
#   COMMAND ${CMAKE_COMMAND} -E echo_append "Building API Documentation..."
#   COMMAND ${DOXYGEN_EXECUTABLE} ${DOXYGEN_INPUT}
#   COMMAND ${CMAKE_COMMAND} -E echo "Done."
#   WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})

ENDIF()


