IF(IS_DIRECTORY ".git")
  FIND_PROGRAM(GIT_EXECUTABLE git)
  IF(GIT_EXECUTABLE)
    EXECUTE_PROCESS(COMMAND ${GIT_EXECUTABLE} "submodule" "init")
    EXECUTE_PROCESS(COMMAND ${GIT_EXECUTABLE} "submodule"
    OUTPUT_VARIABLE GIT_SUBMODULE_STATUS)
    MESSAGE(STATUS "Updating git submodules ")
    MESSAGE(${GIT_SUBMODULE_STATUS})
  ELSE(GIT_EXECUTABLE)
    MESSAGE("WARNING: Could not find git binary, submodules not updated")
  ENDIF(GIT_EXECUTABLE)
ENDIF(IS_DIRECTORY ".git")

