cmake_minimum_required(VERSION 2.6)

# Some status information at build time
message("CMake: ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}-${CMAKE_CACHE_RELEASE_VERSION}")
IF(SWIG_EXECUTABLE)
  message("SWIG: ${SWIG_EXECUTABLE} version ${SWIG_VERSION}")
ENDIF(SWIG_EXECUTABLE)

message("Biolib building on system: ${CMAKE_SYSTEM_PROCESSOR} ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION}")
message("  Build type: ${CMAKE_BUILD_TYPE} for ${CMAKE_HOST_SYSTEM_PROCESSOR}")

FIND_PROGRAM(DATE_EXECUTABLE date)
IF(DATE_EXECUTABLE)
  EXECUTE_PROCESS(COMMAND ${DATE_EXECUTABLE})
ENDIF(DATE_EXECUTABLE)

