
message(STATUS "PerlMacros.cmake")

MACRO(BUILD_PERL_BINDINGS)
  POST_BUILD_PERL_BINDINGS()
ENDMACRO(BUILD_PERL_BINDINGS)

MACRO(POST_BUILD_PERL_BINDINGS)
  # copy .pm to module directory
  ADD_CUSTOM_COMMAND(
    TARGET ${M_MODULE}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${M_NAME}.pm ${MAP_projectname}/${M_NAME}.pm
  )

  # Make sure it gets cleaned up
  SET_DIRECTORY_PROPERTIES(PROPERTIES  
    ADDITIONAL_MAKE_CLEAN_FILES "${M_NAME}.pm;${MAP_projectname}/${M_NAME}.pm;build/${M_NAME}.xml;output/perl/${M_NAME}.pod;build/${M_NAME}.html;pod2htmd.tmp;pod2htmi.tmp") 

  IF(APPLE)
    ADD_CUSTOM_COMMAND(
      TARGET ${M_MODULE}
      POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy lib${M_NAME}.so ${M_NAME}.dylib
    )
  ENDIF(APPLE)
ENDMACRO(POST_BUILD_PERL_BINDINGS)

# Set up a test
MACRO(TEST_PERL_BINDINGS)

  ENABLE_TESTING()

  IF(CYGWIN)
    SET(_SEARCHPATH env PATH=${MODULE_LIBRARY_BINPATH}:$ENV{PATH})
  ENDIF(CYGWIN)

  ADD_TEST(TestPerl${M_NAME} ${_SEARCHPATH} ${PERL_EXECUTABLE} -I../${M_NAME}/${MAP_projectname} ./../test/test_${M_NAME}.pl)
  SET(_SEARCHPATH unknown)

ENDMACRO(TEST_PERL_BINDINGS)

# Installation location for the PERL module
MACRO(INSTALL_PERL_BINDINGS)

  INSTALL(FILES ${M_MODULE}.pm DESTINATION ${PERL_LIB_PATH}/${MAP_projectname} )

  IF(APPLE)
    INSTALL(FILES ${M_MODULE}.dylib DESTINATION ${PERL_LIB_PATH} )
  ENDIF(APPLE)

  INSTALL(TARGETS ${M_MODULE} 
    LIBRARY DESTINATION ${PERL_SLIB_PATH}
    ARCHIVE DESTINATION ${PERL_SLIB_PATH}/${MAP_projectname}
    RUNTIME DESTINATION bin )

ENDMACRO(INSTALL_PERL_BINDINGS)
