
message(STATUS "PerlMacros.cmake")

MACRO(POST_BUILD_PERL_BINDINGS)
  # copy .pm to module directory
  ADD_CUSTOM_COMMAND(
    TARGET ${M_MODULE}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy ${M_NAME}.pm ${MAP_projectname}/${M_NAME}.pm
  )
  IF(APPLE)
    ADD_CUSTOM_COMMAND(
      TARGET ${M_MODULE}
      POST_BUILD
      COMMAND ${CMAKE_COMMAND} -E copy ${M_NAME}.so ${M_NAME}.dylib
    )
  ENDIF(APPLE)
ENDMACRO(POST_BUILD_PERL_BINDINGS)

# Set up a test
MACRO(TEST_PERL_BINDINGS)

  IF(CYGWIN)
    GET_FILENAME_COMPONENT(_SEARCHPATH ${MODULE_LIBRARY} PATH)
    SET(_SEARCHPATH env PATH=${_SEARCHPATH}:$PATH)
  ENDIF(CYGWIN)

  ADD_TEST(TestPerl${M_NAME} ${_SEARCHPATH} ${PERL_EXECUTABLE} -I../${M_NAME}/biolib ./../test/test_${M_NAME}.pl)
  SET(_SEARCHPATH unknown)

ENDMACRO(TEST_PERL_BINDINGS)

# Installation location for the PERL module
MACRO(INSTALL_PERL_BINDINGS)

  INSTALL(FILES ${M_MODULE}.pm DESTINATION ${PERL_LIB_PATH}/${MAP_projectname} )

  IF(APPLE)
    INSTALL(FILES ${M_MODULE}.dylib DESTINATION ${PERL_LIB_PATH} )
  ENDIF(APPLE)

  INSTALL(TARGETS ${M_MODULE} 
    LIBRARY DESTINATION ${PERL_SLIB_PATH}
    ARCHIVE DESTINATION ${PERL_SLIB_PATH}/${MAP_projectname}
    RUNTIME DESTINATION bin )

ENDMACRO(INSTALL_PERL_BINDINGS)
