
message(STATUS "RubyMacros.cmake")

# Set up a test
MACRO(TEST_RUBY_BINDINGS)

  IF(CYGWIN)
    GET_FILENAME_COMPONENT(_SEARCHPATH ${MODULE_LIBRARY} PATH)
    SET(_SEARCHPATH env PATH=${_SEARCHPATH}:$PATH)
  ENDIF(CYGWIN)

  ADD_TEST(TestRuby${M_NAME} ${_SEARCHPATH} ${RUBY_EXECUTABLE} -I../${M_NAME} ./../test/test_${M_NAME}.rb)
  SET(_SEARCHPATH unknown)

ENDMACRO(TEST_RUBY_BINDINGS)

# Installation location for the Ruby module
MACRO(INSTALL_RUBY_BINDINGS)

  INSTALL(TARGETS ${M_MODULE} 
    LIBRARY DESTINATION ${RUBY_LIB_PATH}/${MAP_projectname}
    ARCHIVE DESTINATION ${RUBY_LIB_PATH}/${MAP_projectname}
    RUNTIME DESTINATION bin )

ENDMACRO(INSTALL_RUBY_BINDINGS)
