
message(STATUS "RubyMacros.cmake")

MACRO(TEST_RUBY_BINDINGS)

ADD_TEST(Ruby_${M_NAME} env PATH=${MODULE_SOURCE_PATH}:$PATH ${RUBY_EXECUTABLE}
 -I../${M_NAME} ./../test/test_${M_NAME}.rb)

ENDMACRO(TEST_RUBY_BINDINGS)

# Installation location for the Ruby module
MACRO(INSTALL_RUBY_BINDINGS)

  INSTALL(TARGETS ${M_MODULE} 
    LIBRARY DESTINATION ${RUBY_LIB_PATH}/${MAP_projectname}
    ARCHIVE DESTINATION ${RUBY_LIB_PATH}/${MAP_projectname}
    RUNTIME DESTINATION bin )

ENDMACRO(INSTALL_RUBY_BINDINGS)
