#! /usr/bin/ruby
#
#  Clone and test CMake trees on virtual machines using ssh. See
#  ./doc/TESTING.txt for more info.
#
#  The testing configuration is picked up from a YAML file passed in
#  as the first argument.
#
#  Pjotr Prins (c) 2009
#

require 'yaml'

cmake_support_path = File.dirname(File.dirname(__FILE__))

def msg action, term=''
	print (action+': ').ljust(12),term,"\n"
end

msg "Running","cmake-support/scripts/fulltest"
msg "From",cmake_support_path

if ARGV.size == 0
  error "Usage: ./tools/cmake-support/scripts/fulltest configfn\n"
end

configfn = ARGV.shift
msg 'Parsing',configfn

config = YAML::load( File.open(configfn) )
p config
config.each do | item |
  msg 'Test',item[:name]
	cmd = "scp -P #{item[:port]} #{item[:script]} #{item[:user]}@#{item[:host]}:"
	msg 'Copy',cmd
  Kernel.system(cmd)
	cmd = "ssh -p #{item[:port]} #{item[:user]}@#{item[:host]} ./#{File.basename(item[:script])} #{item[:project]} #{item[:git]}"
	msg 'Run',cmd
  Kernel.system(cmd)
	cmd = "scp -P #{item[:port]} #{item[:user]}@#{item[:host]}:autotest/#{item[:project]}/test.out #{item[:name]}.result"
	msg 'Fetch',cmd
	cmd = "scp -P #{item[:port]} #{item[:user]}@#{item[:host]}:autotest/#{item[:project]}/testlog.out #{item[:name]}.log"
	msg 'Fetch',cmd
end
